### ISSUE TITLE
empty screen on the hybrid graphics laptop

### ISSUE THREAD

**Issue by PanAeon** [any1/wlvncc#35] opened 2024-10-29 21:17 UTC
Hi,
when I open the `wlvncc` on my hybrid graphics laptop (nvidia + intel) I see only a transparent window. When I try to run it on the Nvidia with `nvidia-offload` the result is the same. But when I supply `-s` option the window renders correctly. Desktop environment `sway`

**Comment by any1** [comment] 2024-10-30 11:34
This is a duplicate of #19

**Closed** 2024-10-30 11:34 UTC
Labels: duplicate
